//MISAL DIGUNAKAN UNTUK USER ATAU MEYAKINKAN USER JIKA PADA KASUS MENGHAPUS DATA

x= confirm('apakah yakin ingin menghapus');
alert(x);

//NILAI YANG DIKELUARKAN OLEH CONFIRM ADALAH BOOLEAN 
//TRUE OR FALSE